package blackjack;

public class Card {

	private int suit;
	private int rank;
	private int value;
	private static final String[] suits = {"Clubs", "Diamonds", "Hearts", "Spades"};
    private static final String[] ranks = {"Ace", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten", "Jack", "Queen", "King"};

	
    public Card(int suit,int rank){
    	this.suit = suit;
    	this.rank = rank;	
    }
	public Card(int suit,int rank,int value){
		this.suit = suit;
		this.rank = rank;
		this.value = value;
		
	}
	// Copy constructor // a must for the GUI
	public Card(Card card) {
		// TODO Auto-generated constructor stub
		this.suit = card.suit;
		this.rank = card.rank;
		this.value = card.value;
	}

	public Card() {
		// TODO Auto-generated constructor stub
	}
	// Getters for the attributes // a must for the GUI “autogenerated not written by hand”
	public int getSuit() { return suit; }
	public int getRank() { return rank; }
	public int getValue() { return valueOf(); }
	
	private int valueOf(){
		//returns the value of the Card
		if (this.rank < 10){
		return rank + 1;
		}
		if(this.rank >=10){
		return 10;
		}
		else{
		return 0;
		}
	}
	
	
	
	public String toString(){
		//returns a String representing the Card in form "Ace/Three/King of Hearts"
	        return ranks[this.rank] + " of " + suits[this.suit];
	}
	
	
}
